freebsd_task:
  freebsd_instance:
    image_family: freebsd-15-0-amd64-ufs
  timeout_in: 5m
  matrix:
    env:
      QTHREADS_SCHEDULER: nemesis
    env:
      QTHREADS_SCHEDULER: sherwood
    env:
      QTHREADS_SCHEDULER: distrib
  install_deps_script: |
    pkg install -y llvm cmake
    pkg install -y coreutils # to get gtimeout for CI. The built-in timeout sometimes fails to kill the process.
  build_script: |
    mkdir build
    cd build
    cmake -DCMAKE_BUILD_TYPE=Release -DQTHREADS_SCHEDULER=$QTHREADS_SCHEDULER -DQTHREADS_TOPOLOGY=no -DQTHREADS_CONTEXT_SWAP_IMPL=system ..
    make -j$CIRRUS_CPU VERBOSE=1
  test_script: |
    cd build
    CTEST_OUTPUT_ON_FAILURE=1 gtimeout --foreground -k 10s 2m make test VERBOSE=1

