
version: 2.1

jobs:
  arm_gcc:
    parameters:
      scheduler:
        type: string
      topology:
        type: string
    machine:
      image: ubuntu-2404:edge
    resource_class: arm.medium
    environment:
      CC: gcc-14
      CXX: g++-14
    steps:
      - checkout
      - run: |
          sudo apt-add-repository -y universe
          sudo apt-get install -y gcc-14 g++-14
          sudo apt-get install -y autoconf automake libtool
          sudo apt-get install -y hwloc libhwloc-dev
      - run: |
          ./autogen.sh
          ./configure --enable-picky --with-scheduler=<< parameters.scheduler >> --with-topology=<< parameters.topology >>
          make -j2
          make tests -j2
      - run:
          command: timeout --foreground -k 10s 2m make check
          no_output_timeout: 180s

  arm_clang:
    parameters:
      scheduler:
        type: string
      topology:
        type: string
    machine:
      image: ubuntu-2404:edge
    resource_class: arm.medium
    environment:
      CC: clang-19
      CXX: clang++-19
    steps:
      - checkout
      - run: |
          sudo apt-add-repository -y universe
          sudo apt-get install -y gcc-14 g++-14
          sudo apt-get install -y autoconf automake libtool
          sudo apt-get install -y hwloc libhwloc-dev
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository -y 'deb https://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main'
          sudo apt-get install -y clang-19
      - run: |
          ./autogen.sh
          ./configure --enable-picky --with-scheduler=<< parameters.scheduler >> -with-topology=<< parameters.topology >>
          make -j2
          make tests -j2
      - run:
          command: timeout --foreground -k 10s 2m make check
          no_output_timeout: 180s

  arm_sanitizers:
    parameters:
      scheduler:
        type: string
      topology:
        type: string
      sanitizer:
        type: string
    machine:
      image: ubuntu-2404:edge
    resource_class: arm.medium
    environment:
      CC: clang-19
      CXX: clang++-19
      CFLAGS: "-fsanitize=<< parameters.sanitizer >> -fno-sanitize-recover=all"
      CXXFLAGS: "-fsanitize=<< parameters.sanitizer >> -fno-sanitize-recover=all"
      LDFLAGS: "-fsanitize=<< parameters.sanitizer >> -fno-sanitize-recover=all"
      QTHREAD_STACK_SIZE: 524288
      ASAN_OPTIONS: "check_initialization_order=1"
    steps:
      - checkout
      - run: |
          sudo apt-add-repository -y universe
          sudo apt-get install -y gcc-14 g++-14
          sudo apt-get install -y autoconf automake libtool
          sudo apt-get install -y hwloc libhwloc-dev
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository -y 'deb https://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main'
          sudo apt-get install -y clang-19
      - run: |
          ./autogen.sh
          ./configure --enable-picky --with-scheduler=<< parameters.scheduler >> -with-topology=<< parameters.topology >>
          make -j2
          make tests -j2
      - run:
          command: timeout --foreground -k 10s 4m make check
          no_output_timeout: 120s

  arm_acfl:
    parameters:
      scheduler:
        type: string
      topology:
        type: string
    machine:
      image: ubuntu-2204:2024.04.4
    resource_class: arm.medium
    environment:
      CC: armclang
      CXX: armclang++
    steps:
      - checkout
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y autoconf automake libtool
          sudo apt-get install -y hwloc libhwloc-dev
          wget -O acfl.tar https://developer.arm.com/-/media/Files/downloads/hpc/arm-compiler-for-linux/24-04/arm-compiler-for-linux_24.04_Ubuntu-22.04_aarch64.tar
          tar -vxf acfl.tar
          ./arm-compiler-for-linux_24.04_Ubuntu-22.04/arm-compiler-for-linux_24.04_Ubuntu-22.04.sh -a -f -s acfl
          rm acfl.tar
          sudo apt install -y ./acfl/gcc-13.2.0_Ubuntu-22.04.deb ./acfl/arm-linux-compiler-24.04_Ubuntu-22.04.deb
          rm -rf acfl
          export PATH=$PATH:/opt/arm/arm-linux-compiler-24.04_Ubuntu-22.04/bin
          armclang -v
      - run: |
          export PATH=$PATH:/opt/arm/arm-linux-compiler-24.04_Ubuntu-22.04/bin
          ./autogen.sh
          ./configure --enable-picky --with-scheduler=<< parameters.scheduler >> -with-topology=<< parameters.topology >>
          make -j2
          make tests -j2
      - run:
          command: |
              export PATH=$PATH:/opt/arm/arm-linux-compiler-24.04_Ubuntu-22.04/bin
              timeout --foreground -k 10s 4m make check
          no_output_timeout: 60s

  nvc:
    parameters:
      worker_type:
        type: string
      scheduler:
        type: string
      topology:
        type: string
    machine:
      image: ubuntu-2404:edge
    resource_class: << parameters.worker_type >>
    environment:
      CC: nvc
      CXX: nvc++
    steps:
      - checkout
      - run: |
          curl https://developer.download.nvidia.com/hpc-sdk/ubuntu/DEB-GPG-KEY-NVIDIA-HPC-SDK | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg
          export MACHINE_TYPE=`uname -m`
          if [ ${MACHINE_TYPE} == 'x86_64' ]; then echo 'deb [signed-by=/usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg] https://developer.download.nvidia.com/hpc-sdk/ubuntu/amd64 /' | sudo tee /etc/apt/sources.list.d/nvhpc.list; fi
          if [ ${MACHINE_TYPE} == 'aarch64' ]; then echo 'deb [signed-by=/usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg] https://developer.download.nvidia.com/hpc-sdk/ubuntu/arm64 /' | sudo tee /etc/apt/sources.list.d/nvhpc.list; fi
          sudo apt-get update -y
          sudo apt-get install -y nvhpc-24-9
          sudo apt-get install -y autoconf automake libtool
          sudo apt-get install -y hwloc libhwloc-dev
      - run: |
          export MACHINE_TYPE=`uname -m`
          if [ ${MACHINE_TYPE} == 'x86_64' ]; then export PATH="$PATH:/opt/nvidia/hpc_sdk/Linux_x86_64/24.9/compilers/bin"; fi
          if [ ${MACHINE_TYPE} == 'aarch64' ]; then export PATH="$PATH:/opt/nvidia/hpc_sdk/Linux_aarch64/24.9/compilers/bin"; fi
          nvc --version
          ./autogen.sh
          ./configure --enable-picky --disable-fastcontext --with-scheduler=<< parameters.scheduler >> -with-topology=<< parameters.topology >>
          make -j2
          make tests -j2
      - run:
          command: |
              timeout --foreground -k 10s 4m make check
          no_output_timeout: 60s

  musl:
    parameters:
      worker_type:
        type: string
      scheduler:
        type: string
      topology:
        type: string
    docker:
      - image: alpine:latest
    resource_class: << parameters.worker_type >>
    steps:
      - checkout
      - run: |
          apk add --no-cache --no-progress bash make musl-dev hwloc-dev libtool autoconf automake gcc g++
      - run: |
          bash autogen.sh
          bash configure --enable-picky --with-scheduler=<< parameters.scheduler >> -with-topology=<< parameters.topology >>
          make -j2
          make tests -j2
      - run:
          command: make check
          no_output_timeout: 60s

workflows:
  build_and_test:
    jobs:
      - arm_gcc:
          matrix:
            parameters:
              scheduler: [nemesis, sherwood, distrib]
              topology: ['no', binders, hwloc]
      - arm_clang:
          matrix:
            parameters:
              scheduler: [nemesis, sherwood, distrib]
              topology: ['no', binders, hwloc]
      - arm_sanitizers:
          matrix:
            parameters:
              scheduler: [nemesis, sherwood, distrib]
              topology: ['no', binders, hwloc]
              sanitizer: [address, memory, thread, undefined]
            exclude:
              - scheduler: nemesis
                topology: binders
                sanitizer: memory
              - scheduler: sherwood
                topology: binders
                sanitizer: memory
              - scheduler: distrib
                topology: binders
                sanitizer: memory
              - scheduler: nemesis
                topology: hwloc
                sanitizer: memory
              - scheduler: sherwood
                topology: hwloc
                sanitizer: memory
              - scheduler: distrib
                topology: hwloc
                sanitizer: memory
      - arm_acfl:
          matrix:
            parameters:
              scheduler: [nemesis, sherwood, distrib]
              topology: ['no', binders, hwloc]
      - nvc:
          matrix:
            parameters:
              worker_type: [medium, arm.medium]
              scheduler: [nemesis, sherwood, distrib]
              topology: ['no', binders, hwloc]
      - musl:
          matrix:
            parameters:
              worker_type: [medium, arm.medium]
              scheduler: [nemesis, sherwood, distrib]
              topology: ['no', binders, hwloc]

