
version: 2.1

jobs:
  arm_acfl:
    machine:
      image: ubuntu-2204:2024.04.4
    resource_class: arm.medium
    environment:
      CC: armclang
      CXX: armclang++
    steps:
      - run: |
          export REPO_HTTPS=`echo "$CIRCLE_REPOSITORY_URL" | sed "s|git@github.com:|https://github.com/|g"`
          git clone -b "$CIRCLE_BRANCH" "$REPO_HTTPS" . --depth=1
      - run: |
          # Set up apt to get a more recent CMake directly from Kitware.
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
          echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
          sudo apt-get update -y
          sudo apt-get install -y cmake
          sudo apt-get install -y hwloc libhwloc-dev
          wget -O acfl.tar https://developer.arm.com/-/cdn-downloads/permalink/Arm-Compiler-for-Linux/Version_24.10.1/arm-compiler-for-linux_24.10.1_Ubuntu-22.04_aarch64.tar
          tar -vxf acfl.tar
          ls
          ls arm-compiler-for-linux_24.10.1_Ubuntu-22.04
          ./arm-compiler-for-linux_24.10.1_Ubuntu-22.04/arm-compiler-for-linux_24.10.1_Ubuntu-22.04.sh -a -f -s acfl
          rm acfl.tar
          ls acfl
          sudo apt install -y ./acfl/gcc-14.2.0_Ubuntu-22.04.deb ./acfl/arm-linux-compiler-24.10.1_Ubuntu-22.04.deb
          rm -rf acfl
          export PATH=$PATH:/opt/arm/arm-linux-compiler-24.10.1_Ubuntu-22.04/bin
          armclang -v
      - run:
          command: |
              export PATH=$PATH:/opt/arm/arm-linux-compiler-24.10.1_Ubuntu-22.04/bin
              for sch in nemesis sherwood distrib
              do
                  for topo in hwloc binders no
                  do
                      echo "********** Scheduler: $sch, Topology: $topo **********"
                      rm -rf build
                      mkdir build
                      cd build
                      cmake -DCMAKE_BUILD_TYPE=Release -DQTHREADS_SCHEDULER="$sch" -DQTHREADS_TOPOLOGY="$topo" ..
                      make -j2 VERBOSE=1
                      CTEST_OUTPUT_ON_FAILURE=1 timeout -k 10s --foreground 4m make test VERBOSE=1
                      cd ..
                  done
              done
          no_output_timeout: 180s

  nvc:
    parameters:
      worker_type:
        type: string
    machine:
      image: ubuntu-2404:edge
    resource_class: << parameters.worker_type >>
    environment:
      CC: nvc
      CXX: nvc++
    steps:
      - run: |
          export REPO_HTTPS=`echo "$CIRCLE_REPOSITORY_URL" | sed "s|git@github.com:|https://github.com/|g"`
          git clone -b "$CIRCLE_BRANCH" "$REPO_HTTPS" . --depth=1
      - run: |
          curl https://developer.download.nvidia.com/hpc-sdk/ubuntu/DEB-GPG-KEY-NVIDIA-HPC-SDK | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg
          export MACHINE_TYPE=`uname -m`
          if [ ${MACHINE_TYPE} == 'x86_64' ]; then echo 'deb [signed-by=/usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg] https://developer.download.nvidia.com/hpc-sdk/ubuntu/amd64 /' | sudo tee /etc/apt/sources.list.d/nvhpc.list; fi
          if [ ${MACHINE_TYPE} == 'aarch64' ]; then echo 'deb [signed-by=/usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg] https://developer.download.nvidia.com/hpc-sdk/ubuntu/arm64 /' | sudo tee /etc/apt/sources.list.d/nvhpc.list; fi
          sudo apt-get update -y
          sudo apt-get install -y cmake gcc g++ gfortran hwloc libhwloc-dev
          sudo apt-get install -y nvhpc-26-1
      - run:
          command: |
              export MACHINE_TYPE=`uname -m`
              if [ ${MACHINE_TYPE} == 'x86_64' ]; then export PATH="$PATH:/opt/nvidia/hpc_sdk/Linux_x86_64/26.1/compilers/bin"; fi
              if [ ${MACHINE_TYPE} == 'aarch64' ]; then export PATH="$PATH:/opt/nvidia/hpc_sdk/Linux_aarch64/26.1/compilers/bin"; fi
              nvc --version
              for sch in nemesis sherwood distrib
              do
                  for topo in hwloc binders no
                  do
                      echo "********** Scheduler: $sch, Topology: $topo **********"
                      rm -rf build
                      mkdir build
                      cd build
                      cmake -DCMAKE_BUILD_TYPE=Release -DQTHREADS_SCHEDULER="$sch" -DQTHREADS_TOPOLOGY="$topo" ..
                      make -j2 VERBOSE=1
                      CTEST_OUTPUT_ON_FAILURE=1 timeout -k 10s --foreground 4m make test VERBOSE=1
                      cd ..
                  done
              done
          no_output_timeout: 180s

  musl:
    parameters:
      worker_type:
        type: string
    docker:
      - image: alpine:latest
    resource_class: << parameters.worker_type >>
    steps:
      - run: |
          apk add --no-cache --no-progress git
          export REPO_HTTPS=`echo "$CIRCLE_REPOSITORY_URL" | sed "s|git@github.com:|https://github.com/|g"`
          git clone -b "$CIRCLE_BRANCH" "$REPO_HTTPS" . --depth=1
      - run: |
          apk add --no-cache --no-progress bash make musl-dev hwloc-dev cmake gcc g++ clang linux-headers
      - run:
          command: |
              for compiler in clang gcc
              do
                  if [ "$compiler" = "gcc" ]; then export CC=gcc && export CXX=g++; fi
                  if [ "$compiler" = "clang" ]; then export CC=clang && export CXX=clang++; fi
                  for sch in nemesis sherwood distrib
                  do
                      for topo in hwloc binders no
                      do
                          echo "********** Scheduler: $sch, Topology: $topo **********"
                          rm -rf build
                          mkdir build
                          cd build
                          cmake -DCMAKE_BUILD_TYPE=Release -DQTHREADS_SCHEDULER="$sch" -DQTHREADS_TOPOLOGY="$topo" ..
                          make -j2 VERBOSE=1
                          CTEST_OUTPUT_ON_FAILURE=1 make test VERBOSE=1
                          cd ..
                      done
                  done
              done
          no_output_timeout: 180s

workflows:
  build_and_test:
    jobs:
      - arm_acfl
      - nvc:
          matrix:
            parameters:
              worker_type: [medium, arm.medium]
      - musl:
          matrix:
            parameters:
              worker_type: [medium, arm.medium]

